name: 'SubmitSigningRequest'
description: ''
inputs:
  CIUserToken:  
    description: ''
    required: true
    default: ''
  OrganizationId:  
    description: ''
    required: false
    default: ''
  ProjectSlug:  
    description: ''
    required: false
    default: ''
  SigningPolicySlug: 
    description: ''
    required: false
    default: ''
  ArtifactConfigurationSlug:  
    description: ''
    required: false
    default: ''
  Artifact: 
    description: ''
    required: false
    default: ''
  ArtifactName: 
    description: ''
    required: false
    default: ''
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
